/* 2030 Compass — a local, bilingual career discovery experience. */
const STORAGE_KEY = '2030-compass-state-v2';
const LEGACY_STORAGE_KEY = '2030-compass-state-v1';
const TOTAL_QUESTIONS = 10;
const ANSWERS_PER_QUESTION = 4;

const icons = {
  engineering: '⚙', technology: '◈', sustainability: '⌁', healthcare: '♡',
  business: '▥', education: '▤', creative: '✦', community: '◉',
  discover: '⌖', match: '◎', explore: '◌', build: '⌂', people: '◉',
  innovation: '☼', print: '⇩', share: '⌘', check: '✓', arrow: '→'
};

const fields = [
  { id: 'engineering', icon: 'engineering', color: '#be914e', art: 'assets/illustrations/field-engineering.svg', en: { name: 'Engineering & Infrastructure', short: 'Engineering', desc: 'Build the foundations of a connected and advanced nation.', impact: 'Design resilient infrastructure, smart cities, and systems that keep Saudi Arabia moving.', majors: ['Civil Engineering', 'Mechanical Engineering', 'Urban Planning', 'Architecture'], careers: ['Infrastructure Engineer', 'Smart Cities Planner', 'Civil Engineer', 'Project Engineer'], strengths: ['Systems Thinking', 'Practical Problem Solving', 'Analytical Mindset', 'Applied Innovation'] }, ar: { name: 'الهندسة والبنية التحتية', short: 'الهندسة', desc: 'ابنِ أسس وطن مترابط ومتقدم.', impact: 'صمّم بنية تحتية مرنة ومدنًا ذكية وأنظمة تدفع المملكة إلى الأمام.', majors: ['الهندسة المدنية', 'الهندسة الميكانيكية', 'التخطيط الحضري', 'الهندسة المعمارية'], careers: ['مهندس بنية تحتية', 'مخطط مدن ذكية', 'مهندس مدني', 'مهندس مشاريع'], strengths: ['التفكير المنظومي', 'حل المشكلات العملية', 'العقلية التحليلية', 'الابتكار التطبيقي'] } },
  { id: 'technology', icon: 'technology', color: '#557c91', art: 'assets/illustrations/field-technology.svg', en: { name: 'Technology & Digital', short: 'Technology', desc: 'Drive innovation through digital transformation.', impact: 'Lead digital transformation through data, artificial intelligence, and human-centred technology.', majors: ['Computer Science', 'Artificial Intelligence', 'Cybersecurity', 'Data Science'], careers: ['AI Engineer', 'Data Scientist', 'Cybersecurity Analyst', 'Product Manager'], strengths: ['Innovative Thinking', 'Analytical Mindset', 'Curiosity', 'Digital Fluency'] }, ar: { name: 'التقنية والتحول الرقمي', short: 'التقنية', desc: 'قد الابتكار من خلال التحول الرقمي.', impact: 'قد التحول الرقمي بالبيانات والذكاء الاصطناعي والتقنية المتمحورة حول الإنسان.', majors: ['علوم الحاسب', 'الذكاء الاصطناعي', 'الأمن السيبراني', 'علم البيانات'], careers: ['مهندس ذكاء اصطناعي', 'عالم بيانات', 'محلل أمن سيبراني', 'مدير منتج'], strengths: ['التفكير الابتكاري', 'العقلية التحليلية', 'الفضول', 'الطلاقة الرقمية'] } },
  { id: 'sustainability', icon: 'sustainability', color: '#315f4e', art: 'assets/illustrations/field-sustainability.svg', en: { name: 'Sustainability & Environment', short: 'Sustainability', desc: 'Create a greener, more resilient Saudi Arabia for future generations.', impact: 'Create practical solutions for clean energy, resilient communities, and a healthier planet.', majors: ['Environmental Science', 'Sustainable Urban Planning', 'Environmental Engineering', 'Renewable Energy'], careers: ['Sustainability Engineer', 'Renewable Energy Specialist', 'Environmental Consultant', 'Green Infrastructure Planner'], strengths: ['Environmental Awareness', 'Innovative Thinking', 'Empathy & Social Impact', 'Analytical Mindset'] }, ar: { name: 'الاستدامة والبيئة', short: 'الاستدامة', desc: 'اصنع مملكة أكثر خضرة ومرونة للأجيال القادمة.', impact: 'ابتكر حلولًا عملية للطاقة النظيفة والمجتمعات المرنة وكوكب أكثر صحة.', majors: ['العلوم البيئية', 'التخطيط الحضري المستدام', 'الهندسة البيئية', 'الطاقة المتجددة'], careers: ['مهندس استدامة', 'أخصائي طاقة متجددة', 'استشاري بيئي', 'مخطط بنية تحتية خضراء'], strengths: ['الوعي البيئي', 'التفكير الابتكاري', 'التعاطف والأثر المجتمعي', 'العقلية التحليلية'] } },
  { id: 'healthcare', icon: 'healthcare', color: '#bc806e', art: 'assets/illustrations/field-healthcare.svg', en: { name: 'Healthcare & Life Sciences', short: 'Healthcare', desc: 'Improve lives through innovative and compassionate care.', impact: 'Advance healthier communities through care, science, and medical innovation.', majors: ['Medicine', 'Nursing', 'Biomedical Science', 'Public Health'], careers: ['Doctor', 'Biomedical Researcher', 'Public Health Specialist', 'Healthcare Innovator'], strengths: ['Empathy & Social Impact', 'Scientific Curiosity', 'Careful Observation', 'Resilience'] }, ar: { name: 'الرعاية الصحية وعلوم الحياة', short: 'الرعاية الصحية', desc: 'حسّن حياة الناس بالرعاية المبتكرة والرحيمة.', impact: 'طوّر مجتمعات أكثر صحة عبر الرعاية والعلم والابتكار الطبي.', majors: ['الطب', 'التمريض', 'العلوم الطبية الحيوية', 'الصحة العامة'], careers: ['طبيب', 'باحث طبي حيوي', 'أخصائي صحة عامة', 'مبتكر في الرعاية الصحية'], strengths: ['التعاطف والأثر المجتمعي', 'الفضول العلمي', 'الملاحظة الدقيقة', 'المرونة'] } },
  { id: 'business', icon: 'business', color: '#736085', art: 'assets/illustrations/field-business.svg', en: { name: 'Business & Finance', short: 'Business', desc: 'Power economic growth and create new opportunities.', impact: 'Transform ideas into thriving ventures, jobs, and opportunities for Saudi Arabia.', majors: ['Business Administration', 'Finance', 'Marketing', 'Economics'], careers: ['Entrepreneur', 'Financial Analyst', 'Business Strategist', 'Investment Associate'], strengths: ['Leadership', 'Strategic Thinking', 'Communication', 'Opportunity Spotting'] }, ar: { name: 'الأعمال والتمويل', short: 'الأعمال', desc: 'عزّز النمو الاقتصادي واصنع فرصًا جديدة.', impact: 'حوّل الأفكار إلى مشاريع مزدهرة ووظائف وفرص للمملكة العربية السعودية.', majors: ['إدارة الأعمال', 'التمويل', 'التسويق', 'الاقتصاد'], careers: ['رائد أعمال', 'محلل مالي', 'استراتيجي أعمال', 'مساعد استثمار'], strengths: ['القيادة', 'التفكير الاستراتيجي', 'التواصل', 'اكتشاف الفرص'] } },
  { id: 'education', icon: 'education', color: '#aa8cb2', art: 'assets/illustrations/field-education.svg', en: { name: 'Education & Research', short: 'Education', desc: 'Shape future minds through knowledge and discovery.', impact: 'Open new pathways to knowledge, lifelong learning, and meaningful discovery.', majors: ['Education', 'Psychology', 'Research Science', 'Instructional Design'], careers: ['Teacher', 'Researcher', 'Learning Designer', 'Education Policy Specialist'], strengths: ['Curiosity', 'Communication', 'Patience', 'Knowledge Sharing'] }, ar: { name: 'التعليم والبحث', short: 'التعليم', desc: 'شكّل عقول المستقبل بالمعرفة والاكتشاف.', impact: 'افتح مسارات جديدة للمعرفة والتعلم المستمر والاكتشاف الهادف.', majors: ['التربية', 'علم النفس', 'البحث العلمي', 'التصميم التعليمي'], careers: ['معلم', 'باحث', 'مصمم تعلّم', 'أخصائي سياسات تعليمية'], strengths: ['الفضول', 'التواصل', 'الصبر', 'مشاركة المعرفة'] } },
  { id: 'creative', icon: 'creative', color: '#b37c75', art: 'assets/illustrations/field-creative.svg', en: { name: 'Creative Industries & Tourism', short: 'Creative', desc: 'Celebrate culture, creativity, and global connections.', impact: 'Share Saudi culture with the world through original experiences, stories, and design.', majors: ['Graphic Design', 'Film & Media', 'Hospitality Management', 'Tourism'], careers: ['Creative Director', 'Experience Designer', 'Tourism Specialist', 'Media Producer'], strengths: ['Creative Expression', 'Storytelling', 'Cultural Awareness', 'Collaboration'] }, ar: { name: 'الصناعات الإبداعية والسياحة', short: 'الإبداع', desc: 'احتفِ بالثقافة والإبداع والتواصل العالمي.', impact: 'شارك الثقافة السعودية مع العالم بتجارب وقصص وتصميمات أصيلة.', majors: ['التصميم الجرافيكي', 'السينما والإعلام', 'إدارة الضيافة', 'السياحة'], careers: ['مدير إبداعي', 'مصمم تجارب', 'أخصائي سياحة', 'منتج إعلامي'], strengths: ['التعبير الإبداعي', 'رواية القصص', 'الوعي الثقافي', 'التعاون'] } },
  { id: 'community', icon: 'community', color: '#718e96', art: 'assets/illustrations/field-community.svg', en: { name: 'Community & Public Service', short: 'Community', desc: 'Build stronger, more inclusive communities across the Kingdom.', impact: 'Bring people together to create a fairer, more connected, and more vibrant society.', majors: ['Public Policy', 'Social Work', 'International Relations', 'Community Development'], careers: ['Public Service Officer', 'Community Programme Lead', 'Policy Analyst', 'Social Impact Consultant'], strengths: ['Empathy & Social Impact', 'Leadership', 'Communication', 'Collaboration'] }, ar: { name: 'المجتمع والخدمة العامة', short: 'المجتمع', desc: 'ابنِ مجتمعات أقوى وأكثر شمولًا في أنحاء المملكة.', impact: 'اجمع الناس لبناء مجتمع أكثر عدلًا وترابطًا وحيوية.', majors: ['السياسة العامة', 'الخدمة الاجتماعية', 'العلاقات الدولية', 'تنمية المجتمع'], careers: ['موظف خدمة عامة', 'قائد برامج مجتمعية', 'محلل سياسات', 'استشاري أثر اجتماعي'], strengths: ['التعاطف والأثر المجتمعي', 'القيادة', 'التواصل', 'التعاون'] } }
];

const question = (enQ, arQ, answers) => ({ en: { q: enQ, help: 'Choose the answer that feels most like you.', a: answers.map(item => [item[0], item[1]]) }, ar: { q: arQ, help: 'اختر الإجابة الأقرب إلى ما يشبهك.', a: answers.map(item => [item[2], item[3]]) }, weights: answers.map(item => item[4]) });
const questions = [
  question('What kind of challenge excites you the most?', 'أي نوع من التحديات يحمسك أكثر؟', [['Solving technical or engineering problems', 'Fixing systems, structures, or complex issues', 'حل مشكلات تقنية أو هندسية', 'إصلاح الأنظمة أو الهياكل أو القضايا المعقدة', { engineering: 5, technology: 2 }], ['Helping people improve their health or quality of life', 'Supporting people and making life better', 'مساعدة الناس على تحسين صحتهم أو جودة حياتهم', 'دعم الناس وجعل الحياة أفضل', { healthcare: 5, community: 2 }], ['Creating a new idea, product, or experience', 'Bringing fresh ideas to life', 'ابتكار فكرة أو منتج أو تجربة جديدة', 'إحياء الأفكار الجديدة', { technology: 4, creative: 4, business: 2 }], ['Leading a project and turning ideas into results', 'Organizing work and making things happen', 'قيادة مشروع وتحويل الأفكار إلى نتائج', 'تنظيم العمل وإنجاز المهام', { business: 4, engineering: 2, community: 2 }]]),
  question('Which setting would you most enjoy working in?', 'في أي بيئة ستستمتع بالعمل أكثر؟', [['A research lab or healthcare centre', 'Discovering ways to improve wellbeing', 'مختبر بحثي أو مركز صحي', 'اكتشاف طرق لتحسين الرفاهية', { healthcare: 5, education: 2 }], ['A smart city or engineering site', 'Building systems for the future', 'مدينة ذكية أو موقع هندسي', 'بناء أنظمة للمستقبل', { engineering: 5, sustainability: 2 }], ['A creative studio or cultural destination', 'Designing memorable experiences', 'استوديو إبداعي أو وجهة ثقافية', 'تصميم تجارب لا تُنسى', { creative: 5, business: 1 }], ['A digital innovation hub', 'Using technology to solve everyday problems', 'مركز ابتكار رقمي', 'استخدام التقنية لحل المشكلات اليومية', { technology: 5, business: 2 }]]),
  question('What future change matters most to you?', 'أي تغيير مستقبلي يهمك أكثر؟', [['A healthier, happier society', 'Making care and wellbeing more accessible', 'مجتمع أكثر صحة وسعادة', 'جعل الرعاية والرفاهية أكثر إتاحة', { healthcare: 5, community: 3 }], ['A cleaner and greener planet', 'Protecting natural resources for future generations', 'كوكب أنظف وأكثر خضرة', 'حماية الموارد الطبيعية للأجيال القادمة', { sustainability: 6, engineering: 1 }], ['More opportunity and prosperity', 'Helping new businesses and ideas grow', 'فرص وازدهار أكثر', 'مساعدة الشركات والأفكار الجديدة على النمو', { business: 5, education: 2 }], ['A more connected digital world', 'Making life smarter, safer, and simpler', 'عالم رقمي أكثر اتصالًا', 'جعل الحياة أذكى وأكثر أمانًا وبساطة', { technology: 6, engineering: 1 }]]),
  question('Which strength feels most like you?', 'أي قوة تشبهك أكثر؟', [['I notice patterns and analyse information', 'I like understanding how things work', 'ألاحظ الأنماط وأحلل المعلومات', 'أحب فهم كيفية عمل الأشياء', { technology: 4, engineering: 3, business: 1 }], ['I care deeply about people and their needs', 'I want to make a positive difference', 'أهتم بعمق بالناس واحتياجاتهم', 'أرغب في إحداث فرق إيجابي', { healthcare: 3, community: 4, education: 2 }], ['I imagine fresh possibilities', 'I enjoy making ideas feel real', 'أتخيل إمكانات جديدة', 'أستمتع بتحويل الأفكار إلى واقع', { creative: 5, technology: 2, sustainability: 1 }], ['I bring people together around a goal', 'I like helping a team move forward', 'أجمع الناس حول هدف', 'أحب مساعدة الفريق على التقدم', { business: 3, community: 4, education: 1 }]]),
  question('What would you most like to learn?', 'ماذا تود أن تتعلم أكثر؟', [['How to design sustainable cities', 'Combining design, systems, and environmental care', 'كيفية تصميم مدن مستدامة', 'دمج التصميم والأنظمة والعناية بالبيئة', { sustainability: 5, engineering: 3 }], ['How AI can improve everyday life', 'Creating technology with a human purpose', 'كيف يحسن الذكاء الاصطناعي الحياة اليومية', 'ابتكار تقنية ذات هدف إنساني', { technology: 6, healthcare: 1 }], ['How communities grow stronger', 'Supporting inclusion, connection, and opportunity', 'كيف تصبح المجتمعات أقوى', 'دعم الشمول والتواصل والفرص', { community: 5, education: 2 }], ['How stories shape culture and travel', 'Sharing experiences that inspire people', 'كيف تشكل القصص الثقافة والسفر', 'مشاركة تجارب تلهم الناس', { creative: 5, business: 2 }]]),
  question('When working with others, what role suits you?', 'عند العمل مع الآخرين، أي دور يناسبك؟', [['The practical problem solver', 'Finding a reliable way forward', 'محلّل المشكلات العملي', 'إيجاد طريق موثوق إلى الأمام', { engineering: 4, technology: 2 }], ['The thoughtful listener', 'Making sure people feel included', 'المستمع الواعي', 'التأكد من شعور الجميع بالشمول', { healthcare: 3, community: 4, education: 2 }], ['The idea generator', 'Bringing energy and imagination', 'مولّد الأفكار', 'إضفاء الطاقة والخيال', { creative: 4, technology: 3, business: 1 }], ['The organised leader', 'Turning a shared goal into action', 'القائد المنظم', 'تحويل الهدف المشترك إلى عمل', { business: 4, community: 2, engineering: 1 }]]),
  question('Which project sounds most rewarding?', 'أي مشروع يبدو لك أكثر فائدة؟', [['Creating renewable energy for a neighbourhood', 'A real-world solution with lasting impact', 'إنشاء طاقة متجددة لحي سكني', 'حل عملي ذو أثر مستدام', { sustainability: 6, engineering: 3 }], ['Developing a health innovation', 'Helping people live longer and better', 'تطوير ابتكار صحي', 'مساعدة الناس على العيش مدة أطول وبشكل أفضل', { healthcare: 6, technology: 2 }], ['Starting a mission-driven business', 'Creating opportunity around an important idea', 'بدء مشروع تجاري قائم على رسالة', 'صناعة فرصة حول فكرة مهمة', { business: 5, community: 2, creative: 1 }], ['Creating an experience that celebrates Saudi culture', 'Connecting local stories with the world', 'إنشاء تجربة تحتفي بالثقافة السعودية', 'ربط القصص المحلية بالعالم', { creative: 6, community: 1 }]]),
  question('What kind of impact do you want to leave?', 'ما الأثر الذي تريد أن تتركه؟', [['A stronger environment for future generations', 'A future where nature and people thrive together', 'بيئة أقوى للأجيال القادمة', 'مستقبل تزدهر فيه الطبيعة والناس معًا', { sustainability: 6, community: 1 }], ['Knowledge that helps people grow', 'Making learning and discovery more powerful', 'معرفة تساعد الناس على النمو', 'جعل التعلم والاكتشاف أكثر قوة', { education: 6, community: 1 }], ['A breakthrough that changes what is possible', 'Using science or technology to move forward', 'إنجاز يغير ما هو ممكن', 'استخدام العلم أو التقنية للتقدم', { technology: 4, healthcare: 2, engineering: 2 }], ['A community where everyone can participate', 'Making society more fair and connected', 'مجتمع يستطيع فيه الجميع المشاركة', 'جعل المجتمع أكثر عدلًا وترابطًا', { community: 6, business: 1 }]]),
  question('Which topic would you happily explore for hours?', 'أي موضوع ستستكشفه بسعادة لساعات؟', [['Climate, ecosystems, and clean energy', 'Understanding the systems that support our planet', 'المناخ والأنظمة البيئية والطاقة النظيفة', 'فهم الأنظمة التي تدعم كوكبنا', { sustainability: 6, engineering: 2 }], ['Medicine, biology, and wellbeing', 'Understanding how science can improve lives', 'الطب وعلم الأحياء والرفاهية', 'فهم كيف يحسن العلم حياة الناس', { healthcare: 6, education: 1 }], ['Markets, strategy, and new ventures', 'Finding ways for good ideas to grow', 'الأسواق والاستراتيجية والمشاريع الجديدة', 'إيجاد طرق لنمو الأفكار الجيدة', { business: 6, technology: 1 }], ['Art, design, culture, and media', 'Making meaningful work that people remember', 'الفن والتصميم والثقافة والإعلام', 'صناعة أعمال هادفة يتذكرها الناس', { creative: 6, education: 1 }]]),
  question('Looking toward 2030, what makes you feel most hopeful?', 'عند النظر إلى عام 2030، ما الذي يمنحك أكبر أمل؟', [['Saudi cities that are sustainable and resilient', 'Building a cleaner, smarter future together', 'مدن سعودية مستدامة ومرنة', 'بناء مستقبل أنظف وأذكى معًا', { sustainability: 5, engineering: 3 }], ['Innovation that makes life healthier', 'Using knowledge and care to improve lives', 'ابتكار يجعل الحياة أكثر صحة', 'استخدام المعرفة والرعاية لتحسين الحياة', { healthcare: 5, technology: 2 }], ['Young people creating new opportunities', 'Turning bold ambitions into meaningful change', 'شباب يصنعون فرصًا جديدة', 'تحويل الطموحات الجريئة إلى تغيير هادف', { business: 4, creative: 2, education: 2 }], ['A society that values every person’s contribution', 'Making sure progress includes everyone', 'مجتمع يقدّر مساهمة كل فرد', 'ضمان شمول الجميع في التقدم', { community: 5, education: 3 }]])
];

const combos = [
  { fields: ['sustainability', 'engineering'], en: { name: 'Sustainable Engineering', desc: 'Build innovative solutions for a cleaner, smarter, and more resilient Saudi Arabia.' }, ar: { name: 'الهندسة المستدامة', desc: 'ابنِ حلولًا مبتكرة لمملكة أنظف وأذكى وأكثر مرونة.' } },
  { fields: ['technology', 'healthcare'], en: { name: 'HealthTech Innovation', desc: 'Use human-centred technology to advance healthier lives and stronger care.' }, ar: { name: 'ابتكار التقنية الصحية', desc: 'استخدم تقنية متمحورة حول الإنسان لتعزيز حياة أكثر صحة ورعاية أقوى.' } },
  { fields: ['technology', 'creative'], en: { name: 'Digital Experience Design', desc: 'Create meaningful digital experiences that connect people, culture, and ideas.' }, ar: { name: 'تصميم التجارب الرقمية', desc: 'ابتكر تجارب رقمية هادفة تربط الناس والثقافة والأفكار.' } },
  { fields: ['business', 'community'], en: { name: 'Social Entrepreneurship', desc: 'Build ventures that create opportunity and strengthen communities.' }, ar: { name: 'ريادة الأعمال الاجتماعية', desc: 'ابنِ مشاريع تصنع الفرص وتعزز المجتمعات.' } },
  { fields: ['education', 'technology'], en: { name: 'Future Learning Innovation', desc: 'Design learning experiences that unlock potential for every generation.' }, ar: { name: 'ابتكار تعلم المستقبل', desc: 'صمّم تجارب تعلم تطلق إمكانات كل جيل.' } },
  { fields: ['creative', 'community'], en: { name: 'Cultural Impact', desc: 'Share Saudi stories and create experiences that bring communities together.' }, ar: { name: 'الأثر الثقافي', desc: 'شارك القصص السعودية وابتكر تجارب تجمع المجتمعات.' } },
  { fields: ['engineering', 'technology'], en: { name: 'Smart Infrastructure', desc: 'Shape connected, intelligent systems for a thriving Saudi Arabia.' }, ar: { name: 'البنية التحتية الذكية', desc: 'شكّل أنظمة مترابطة وذكية لمملكة مزدهرة.' } },
  { fields: ['healthcare', 'community'], en: { name: 'Community Wellbeing', desc: 'Improve lives by creating care that is compassionate, accessible, and inclusive.' }, ar: { name: 'رفاه المجتمع', desc: 'حسّن الحياة برعاية رحيمة ومتاحة وشاملة.' } }
];

const copy = {
  en: {
    home: 'Home', how: 'How it works', vision: 'Our Vision', fields: 'Career Fields', faq: 'FAQs', quiz: 'Quiz',
    startJourney: 'Start My 2030 Journey', startQuiz: 'Start the Quiz', continueQuiz: 'Continue the Quiz', next: 'Next', back: 'Back', retake: 'Retake Quiz', view: 'View Details', exploreAll: 'Explore All Career Fields',
    top3: 'Top 3 Results', allFields: 'All Fields', yourPath: 'Your Path', hybrid: 'Hybrid Future Path', passport: 'Your 2030',
    print: 'Download Result Card', share: 'Share My Result', downloadReady: 'Your result card was downloaded.', downloadFailed: 'We could not download your result card. Please try again.', shared: 'Your result message is ready to share.', copied: 'Your result message was copied.', localShare: 'Your result summary is ready. A public link will work after deployment.', shareFailed: 'Copy this result summary manually:',
    question: 'Question', of: 'of', answerNeeded: 'Choose an answer before continuing.', selected: 'Selected',
    homeTitle: 'Saudi Arabia is<br>building its future.<br><span>Where will you build yours?</span>', homeCopy: 'Discover the career path that matches your strengths, interests, and ambitions — and see how you could contribute to the future of Saudi Arabia.',
    howTitle: 'How 2030 Compass Works', howCopy: 'In a few simple steps, discover your strengths, explore real opportunities, and build a future that fits you.',
    visionTitle: 'Our Vision for a<br><span>Thriving Saudi Future</span>', visionCopy: '2030 Compass helps students and young professionals connect personal ambition with national progress, innovation, sustainability, and opportunity.',
    fieldsTitle: 'Explore Diverse Career Fields', fieldsCopy: 'From innovation to sustainability, discover career opportunities that shape a brighter tomorrow and align with Saudi Arabia’s Vision 2030.',
    readyTitle: 'Ready to Discover<br><span>Your Path?</span>', readyCopy: 'Answer 10 simple questions to discover career fields that match your interests, strengths, and aspirations — and see how they connect to a brighter future in Saudi Arabia’s Vision 2030.',
    noWrong: 'No right or wrong answers', noWrongCopy: 'This is about you and what matters to you.', choose: 'Choose what feels most like you', chooseCopy: 'Be honest and select the options that suit you best.', personal: 'Get personalized results', personalCopy: 'Discover your best-fit fields, strengths, majors, and careers.', readyMeta: '10 QUESTIONS · LESS THAN 2 MINUTES · A BRIGHTER FUTURE AWAITS',
    resultsEyebrow: 'Your Results', resultsTitle: 'Your Top 3 Future Fields', resultsCopy: 'Based on your answers, these are the career fields that best match your interests, strengths, and aspirations.',
    mapEyebrow: 'Your Career Map', mapTitle: 'All 8 Future Fields', matchPercentages: 'Your Match Percentages', mapCopy: 'A complete view of how you align with each career field.', whatMeans: 'What This Means', pathTitle: 'Why This Fits You', strengthDNA: 'Your Strength DNA', connection: 'How Your Interests Connect', futureShape: 'A Future You Can Shape',
    hybridTitle: 'Hybrid Future Path', hybridCopy: 'When your top interests align, powerful opportunities emerge at the intersection of fields. Here is a personalized path that blends your strengths and passions.', combination: 'Your Top Field Combination', pathMeans: 'What This Path Means', powerful: 'Why It’s a Powerful Combination', exampleMajors: 'Example Majors', relatedCareers: 'Related Careers',
    passportTitle: '2030 PASSPORT', passportSub: 'A BRIGHTER FUTURE STARTS HERE', topField: 'Your Top Career Field', topStrengths: 'Your Top Strengths', suggestedMajors: 'Suggested Majors', suggestedCareers: 'Suggested Careers', personalStatement: 'Your Personal Statement',
    faqTitle: 'Questions, answered', faqCopy: 'Everything you need to know before you start your 2030 Compass journey.', faqItems: [['What is 2030 Compass?', 'A free career discovery experience that connects your interests with eight future-facing Saudi career fields.'], ['Who is the quiz for?', 'It is designed for students and young professionals exploring their next step.'], ['Are there right or wrong answers?', 'No. Choose what feels most like you; your results reflect your selections.'], ['How are results calculated?', 'Each answer contributes to the same transparent field scoring model, which ranks your strongest matches.'], ['Can I retake the quiz?', 'Yes. Retaking clears only your answers and results; your language and theme stay saved.'], ['Is my result stored or shared?', 'It is stored only in this browser. Sharing sends a result summary, not your personal data.']],
    mobileMenu: 'Open menu', closeMenu: 'Close menu', homeLabel: '2030 Compass home', languageLabel: 'Switch language', themeDark: 'Enable dark mode', themeLight: 'Enable light mode', progressLabel: 'Career journey progress', faqToggle: 'Toggle answer', match: 'Match', publicLink: 'Public link included after deployment.'
  },
  ar: {
    home: 'الرئيسية', how: 'كيف يعمل', vision: 'رؤيتنا', fields: 'المجالات المهنية', faq: 'الأسئلة الشائعة', quiz: 'الاختبار',
    startJourney: 'ابدأ رحلتي نحو 2030', startQuiz: 'ابدأ الاختبار', continueQuiz: 'تابع الاختبار', next: 'التالي', back: 'رجوع', retake: 'أعد الاختبار', view: 'عرض التفاصيل', exploreAll: 'استكشف جميع المجالات',
    top3: 'أفضل 3 نتائج', allFields: 'كل المجالات', yourPath: 'مسارك', hybrid: 'مسارك الهجين', passport: '2030 الخاص بك',
    print: 'تحميل بطاقة النتيجة', share: 'شارك نتيجتي', downloadReady: 'تم تحميل بطاقة النتيجة.', downloadFailed: 'تعذر تحميل بطاقة النتيجة. حاول مرة أخرى.', shared: 'ملخص نتيجتك جاهز للمشاركة.', copied: 'تم نسخ ملخص نتيجتك.', localShare: 'ملخص نتيجتك جاهز. سيعمل الرابط العام بعد النشر.', shareFailed: 'انسخ ملخص النتيجة يدويًا:',
    question: 'السؤال', of: 'من', answerNeeded: 'اختر إجابة قبل المتابعة.', selected: 'تم الاختيار',
    homeTitle: 'المملكة تبني<br>مستقبلها.<br><span>أين ستبني مستقبلك؟</span>', homeCopy: 'اكتشف المسار المهني الذي يوافق نقاط قوتك واهتماماتك وطموحاتك، وتعرّف على دورك في مستقبل المملكة العربية السعودية.',
    howTitle: 'كيف يعمل 2030 Compass', howCopy: 'في خطوات بسيطة، اكتشف نقاط قوتك واستكشف فرصًا حقيقية وابنِ مستقبلًا يناسبك.',
    visionTitle: 'رؤيتنا لمستقبل<br><span>سعودي مزدهر</span>', visionCopy: 'يساعد 2030 Compass الطلاب والمهنيين الشباب على ربط الطموح الشخصي بالتقدم الوطني والابتكار والاستدامة والفرص.',
    fieldsTitle: 'استكشف مجالات مهنية متنوعة', fieldsCopy: 'من الابتكار إلى الاستدامة، اكتشف فرصًا مهنية تصنع غدًا أكثر إشراقًا وتنسجم مع رؤية السعودية 2030.',
    readyTitle: 'هل أنت مستعد لاكتشاف<br><span>مسارك؟</span>', readyCopy: 'أجب عن 10 أسئلة بسيطة لاكتشاف المجالات المهنية التي توافق اهتماماتك ونقاط قوتك وطموحاتك، وتعرّف على صلتها بمستقبل أكثر إشراقًا ضمن رؤية السعودية 2030.',
    noWrong: 'لا توجد إجابات صحيحة أو خاطئة', noWrongCopy: 'الأمر يتعلق بك وبما يهمك.', choose: 'اختر ما يشبهك أكثر', chooseCopy: 'كن صادقًا واختر الخيارات الأنسب لك.', personal: 'احصل على نتائج شخصية', personalCopy: 'اكتشف مجالاتك ونقاط قوتك وتخصصاتك ووظائفك الأنسب.', readyMeta: '10 أسئلة · أقل من دقيقتين · مستقبل أكثر إشراقًا بانتظارك',
    resultsEyebrow: 'نتائجك', resultsTitle: 'أفضل 3 مجالات مستقبلية لك', resultsCopy: 'بناءً على إجاباتك، هذه المجالات المهنية الأكثر توافقًا مع اهتماماتك ونقاط قوتك وطموحاتك.',
    mapEyebrow: 'خريطتك المهنية', mapTitle: 'المجالات المستقبلية الثمانية', matchPercentages: 'نسب التوافق الخاصة بك', mapCopy: 'نظرة كاملة على مدى توافقك مع كل مجال مهني.', whatMeans: 'ماذا يعني هذا', pathTitle: 'لماذا يناسبك هذا', strengthDNA: 'بصمة نقاط قوتك', connection: 'كيف ترتبط اهتماماتك', futureShape: 'مستقبل يمكنك تشكيله',
    hybridTitle: 'مسارك الهجين', hybridCopy: 'عندما تتوافق اهتماماتك العليا، تظهر فرص قوية عند تقاطع المجالات. إليك مسارًا شخصيًا يمزج نقاط قوتك وشغفك.', combination: 'أفضل مجموعة مجالات لك', pathMeans: 'ماذا يعني هذا المسار', powerful: 'لماذا هذا مزيج قوي', exampleMajors: 'تخصصات مقترحة', relatedCareers: 'وظائف مرتبطة',
    passportTitle: 'جواز 2030', passportSub: 'مستقبل أكثر إشراقًا يبدأ هنا', topField: 'مجالك المهني الأعلى', topStrengths: 'أهم نقاط قوتك', suggestedMajors: 'تخصصات مقترحة', suggestedCareers: 'وظائف مقترحة', personalStatement: 'بيانك الشخصي',
    faqTitle: 'إجابات لأسئلتك', faqCopy: 'كل ما تحتاج إلى معرفته قبل أن تبدأ رحلتك مع 2030 Compass.', faqItems: [['ما هو 2030 Compass؟', 'تجربة مجانية لاكتشاف المسارات المهنية تربط اهتماماتك بثمانية مجالات سعودية مستقبلية.'], ['لمن صُمّم الاختبار؟', 'صُمّم للطلاب والمهنيين الشباب الذين يستكشفون خطوتهم التالية.'], ['هل توجد إجابات صحيحة أو خاطئة؟', 'لا. اختر ما يشبهك أكثر؛ تعكس النتائج اختياراتك.'], ['كيف تُحسب النتائج؟', 'تسهم كل إجابة في نموذج واحد وواضح لدرجات المجالات، ثم يرتب أقوى توافقاتك.'], ['هل يمكنني إعادة الاختبار؟', 'نعم. تؤدي الإعادة إلى مسح إجاباتك ونتائجك فقط، بينما تظل اللغة والمظهر محفوظين.'], ['هل تُحفظ نتيجتي أو تُشارك؟', 'تُحفظ في هذا المتصفح فقط. ترسل المشاركة ملخص النتيجة وليس بياناتك الشخصية.']],
    mobileMenu: 'فتح القائمة', closeMenu: 'إغلاق القائمة', homeLabel: 'الصفحة الرئيسية لـ 2030 Compass', languageLabel: 'تغيير اللغة', themeDark: 'تفعيل المظهر الداكن', themeLight: 'تفعيل المظهر الفاتح', progressLabel: 'تقدم رحلة المسار المهني', faqToggle: 'تبديل الإجابة', match: 'التوافق', publicLink: 'يُدرج الرابط العام بعد النشر.'
  }
};

function defaultState() { return { version: 2, language: 'en', theme: 'light', screen: 'home', answers: Array(TOTAL_QUESTIONS).fill(null), currentQuestion: 0 }; }
function isValidScreen(value) { return ['home', 'how', 'vision', 'fields', 'faq', 'quiz-intro', 'quiz', 'top3', 'all-fields', 'your-path', 'hybrid', 'passport'].includes(value); }
function validAnswers(value) { return Array.isArray(value) && value.length === TOTAL_QUESTIONS && value.every(answer => answer === null || Number.isInteger(answer) && answer >= 0 && answer < ANSWERS_PER_QUESTION); }
function normalizeState(raw) {
  const base = defaultState();
  const answers = validAnswers(raw?.answers) ? raw.answers : base.answers;
  const firstEmpty = Math.max(0, answers.findIndex(answer => answer === null));
  const fallbackQuestion = firstEmpty === -1 ? TOTAL_QUESTIONS - 1 : firstEmpty;
  let screen = raw?.screen === 'hyprid' ? 'hybrid' : raw?.screen;
  if (!isValidScreen(screen)) screen = base.screen;
  if (['top3', 'all-fields', 'your-path', 'hybrid', 'passport'].includes(screen) && answers.some(answer => answer === null)) screen = 'quiz-intro';
  return { version: 2, language: raw?.language === 'ar' ? 'ar' : 'en', theme: raw?.theme === 'dark' ? 'dark' : 'light', screen, answers, currentQuestion: Math.min(TOTAL_QUESTIONS - 1, Math.max(0, Number.isInteger(raw?.currentQuestion) ? raw.currentQuestion : fallbackQuestion)) };
}
function loadState() {
  try {
    const current = localStorage.getItem(STORAGE_KEY);
    if (current) return normalizeState(JSON.parse(current));
    const legacy = localStorage.getItem(LEGACY_STORAGE_KEY);
    return normalizeState(legacy ? JSON.parse(legacy) : defaultState());
  } catch { return defaultState(); }
}
let state = loadState();
const app = document.getElementById('app');
const toast = document.getElementById('toast');
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function t(key) { return copy[state.language][key]; }
function content(item) { return item[state.language]; }
function field(id) { return fields.find(item => item.id === id); }
function icon(key) { return `<span aria-hidden="true">${icons[key] || '✦'}</span>`; }
function e(value) { return String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function arrow() { return `<span class="direction-arrow" aria-hidden="true">→</span>`; }
function showToast(message) { toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 4600); }
function isComplete() { return state.answers.every(answer => answer !== null); }

function scoreResults() {
  const scores = Object.fromEntries(fields.map(item => [item.id, 0]));
  state.answers.forEach((answerIndex, index) => {
    if (answerIndex === null) return;
    Object.entries(questions[index].weights[answerIndex]).forEach(([id, points]) => { if (id in scores) scores[id] += points; });
  });
  const max = Math.max(...Object.values(scores), 1);
  const ranked = fields.map((item, order) => ({ id: item.id, score: scores[item.id], order })).sort((a, b) => b.score - a.score || a.order - b.order);
  const scoresWithMatch = ranked.map((item, index) => ({ ...item, match: Math.max(40, Math.min(98, Math.round(55 + item.score / max * 40 - index * 2))) }));
  const top = scoresWithMatch.slice(0, 3).map(item => item.id);
  const combo = combos.find(item => item.fields.every(id => top.includes(id))) || combos.find(item => item.fields.every(id => top.slice(0, 2).includes(id))) || combos.find(item => item.fields.includes(top[0])) || combos[0];
  return { scores: scoresWithMatch, top, combo: combo.fields };
}
function results() { return isComplete() ? scoreResults() : null; }
function resultEntry(id) { return results()?.scores.find(item => item.id === id); }
function topEntries() { const current = results(); return current ? current.top.map(id => ({ ...field(id), result: current.scores.find(item => item.id === id) })) : []; }
function comboForResult() { const result = results(); return combos.find(combo => result && combo.fields.every((id, index) => id === result.combo[index])) || combos[0]; }

function goto(screen) {
  const requiresResult = ['top3', 'all-fields', 'your-path', 'hybrid', 'passport'];
  if (requiresResult.includes(screen) && !isComplete()) screen = 'quiz-intro';
  state.screen = screen; save(); render(); window.scrollTo({ top: 0, behavior: 'instant' });
}
function startQuiz() { if (state.answers.every(answer => answer === null)) state.currentQuestion = 0; else state.currentQuestion = Math.min(TOTAL_QUESTIONS - 1, Math.max(0, state.answers.findIndex(answer => answer === null))); state.screen = 'quiz'; save(); render(); }
function resetQuiz() { state.answers = Array(TOTAL_QUESTIONS).fill(null); state.currentQuestion = 0; state.screen = 'quiz-intro'; save(); render(); }
function setLanguage() { state.language = state.language === 'en' ? 'ar' : 'en'; save(); render(); }
function toggleTheme() { state.theme = state.theme === 'light' ? 'dark' : 'light'; save(); render(); }

function brand() { return `<span class="brand-mark"><img src="assets/illustrations/brand-compass.svg?v=2" alt=""></span><span class="brand-copy"><strong>2030 Compass</strong><small>${state.language === 'en' ? 'Find Your Place in the Future' : 'اكتشف مكانك في المستقبل'}</small></span>`; }
function header(active = '') {
  const links = [['home', 'home'], ['how', 'how'], ['vision', 'vision'], ['fields', 'fields'], ['faq', 'faq']];
  return `<header class="site-header"><button class="brand" data-go="home" aria-label="${t('homeLabel')}">${brand()}</button><button class="menu-toggle" data-action="menu" aria-expanded="false" aria-label="${t('mobileMenu')}">☰</button><nav class="top-nav" aria-label="${t('homeLabel')}">${links.map(([id, label]) => `<button class="${active === id ? 'active' : ''}" data-go="${id}">${t(label)}</button>`).join('')}</nav><div class="header-actions"><button class="lang-control" data-action="language" aria-label="${t('languageLabel')}">◎ <b>${state.language === 'en' ? 'EN' : 'عربي'}</b><span>${state.language === 'en' ? 'عربي' : 'EN'}</span></button><button class="theme-toggle" data-action="theme" aria-label="${state.theme === 'light' ? t('themeDark') : t('themeLight')}" aria-pressed="${state.theme === 'dark'}"><span aria-hidden="true">☼</span><span class="knob"></span></button></div></header>`;
}
function scene(className = '') { return `<div class="scene ${className}" aria-hidden="true"><img src="assets/illustrations/future-city.svg" alt=""></div>`; }
function pageShell(active, body, className = '') { return `<div class="site-page ${className}">${header(active)}${scene()}<main id="main-content">${body}</main></div>`; }
function pill(iconName, title, body) { return `<article class="benefit"><span class="round-icon">${icon(iconName)}</span><h3>${title}</h3><p>${body}</p></article>`; }
function progressNav(active) {
  const steps = [['quiz', 'quiz', '1'], ['top3', 'top3', '2'], ['all-fields', 'allFields', '3'], ['your-path', 'yourPath', '4'], ['hybrid', 'hybrid', '5'], ['passport', 'passport', '6']];
  const order = steps.map(item => item[0]); const activeIndex = order.indexOf(active); const complete = isComplete();
  return `<nav class="progress-nav" aria-label="${t('progressLabel')}">${steps.map(([id, key, number], index) => { const done = complete && index < activeIndex; const allowed = id === 'quiz' || complete; return `<button data-go="${id}" data-number="${number}" ${allowed ? '' : 'disabled'} class="progress-step ${active === id ? 'active' : ''} ${done ? 'done' : ''}"><span>${done ? '✓' : number}</span>${t(key)}</button>`; }).join('')}</nav>`;
}
function pageHero(eyebrow, title, text) { return `<section class="page-hero"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${text}</p></div><img src="assets/illustrations/future-city.svg" alt="" aria-hidden="true"></section>`; }

function homeScreen() {
  return pageShell('home', `<section class="hero"><div class="hero-copy"><p class="eyebrow">2030 Compass</p><h1>${t('homeTitle')}</h1><p>${t('homeCopy')}</p><button class="primary-button" data-go="quiz-intro">${t('startJourney')} ${arrow()}</button></div><div class="hero-visual"><img src="assets/illustrations/future-city.svg" alt="" aria-hidden="true"></div></section><section class="benefit-row">${pill('discover', state.language === 'en' ? 'Discover Your Strengths' : 'اكتشف نقاط قوتك', state.language === 'en' ? 'Understand what you enjoy and what you are good at.' : 'تعرّف على ما تستمتع به وما تتقنه.')}${pill('explore', state.language === 'en' ? 'Explore Career Fields' : 'استكشف المجالات المهنية', state.language === 'en' ? 'See real opportunities across eight key sectors.' : 'تعرّف على فرص واقعية عبر ثمانية مجالات رئيسية.')}${pill('build', state.language === 'en' ? 'Build Your Skills' : 'ابنِ مهاراتك', state.language === 'en' ? 'Get tailored recommendations for your future.' : 'احصل على توصيات تناسب مستقبلك.')}${pill('people', state.language === 'en' ? 'Make an Impact' : 'اصنع أثرًا', state.language === 'en' ? 'Be part of a brighter Saudi Arabia.' : 'كن جزءًا من مملكة أكثر إشراقًا.')}</section>`);
}
function howScreen() {
  const steps = state.language === 'en' ? [['discover', '01', 'Discover', 'Understand your interests and strengths.'], ['match', '02', 'Match', 'See the fields that fit you best.'], ['explore', '03', 'Explore', 'Discover majors, careers, and skills.'], ['build', '04', 'Build', 'Create your personalized 2030 future.']] : [['discover', '01', 'اكتشف', 'تعرّف على اهتماماتك ونقاط قوتك.'], ['match', '02', 'طابق', 'شاهد المجالات الأنسب لك.'], ['explore', '03', 'استكشف', 'تعرّف على التخصصات والوظائف والمهارات.'], ['build', '04', 'ابنِ', 'أنشئ مستقبلك الشخصي نحو 2030.']];
  return pageShell('how', `${pageHero('', t('howTitle'), t('howCopy'))}<section class="how-panel">${steps.map((step, index) => `<article class="how-step"><span class="round-icon">${icon(step[0])}</span><small>${step[1]}</small><h2>${step[2]}</h2><p>${step[3]}</p><img src="assets/illustrations/field-${fields[index === 3 ? 1 : index].id}.svg" alt="" aria-hidden="true"></article>`).join('')}</section><div class="center-action"><button class="primary-button" data-go="quiz-intro">${t('startQuiz')} ${arrow()}</button></div>`);
}
function visionScreen() {
  const items = state.language === 'en' ? [['people', 'People First', 'Empower Saudi talent and unlock human potential.'], ['business', 'Opportunity for All', 'Create inclusive pathways for education, careers, and lifelong growth.'], ['innovation', 'Innovation & Technology', 'Drive a knowledge-based economy through creativity and digital transformation.'], ['sustainability', 'Sustainability & Growth', 'Build a greener, more resilient Saudi Arabia for future generations.'], ['healthcare', 'A Thriving Society', 'Foster vibrant communities, richer culture, and a higher quality of life.']] : [['people', 'الإنسان أولًا', 'نمكّن المواهب السعودية ونطلق الطاقات البشرية.'], ['business', 'فرص للجميع', 'نصنع مسارات شاملة للتعليم والعمل والنمو المستمر.'], ['innovation', 'الابتكار والتقنية', 'ندعم اقتصاد المعرفة بالإبداع والتحول الرقمي.'], ['sustainability', 'الاستدامة والنمو', 'نبني مملكة أكثر خضرة ومرونة للأجيال القادمة.'], ['healthcare', 'مجتمع مزدهر', 'نعزز المجتمعات الحيوية والثقافة الثرية وجودة الحياة.']];
  return pageShell('vision', `${pageHero('', t('visionTitle'), t('visionCopy'))}<section class="vision-grid">${items.map((item, index) => `<article class="vision-card"><span class="round-icon">${icon(item[0])}</span><h2>${item[1]}</h2><p>${item[2]}</p><img src="assets/illustrations/field-${fields[index % fields.length].id}.svg" alt="" aria-hidden="true"></article>`).join('')}</section>`);
}
function fieldsScreen() {
  return pageShell('fields', `${pageHero('', t('fieldsTitle'), t('fieldsCopy'))}<section class="field-grid">${fields.map(item => { const x = content(item); return `<article class="field-card"><img src="${item.art}" alt="" aria-hidden="true"><div><span class="round-icon">${icon(item.icon)}</span><h2>${x.name}</h2><p>${x.desc}</p><button class="text-button" data-go="quiz-intro">${t('view')} ${arrow()}</button></div></article>`; }).join('')}</section>`);
}
function faqScreen() {
  const faq = t('faqItems');
  return pageShell('faq', `${pageHero('', t('faqTitle'), t('faqCopy'))}<section class="faq-layout"><div class="faq-list">${faq.map((item, index) => `<article class="faq-item"><button data-action="faq" data-faq="${index}" aria-expanded="false" aria-controls="faq-${index}"><span>${item[0]}</span><span aria-hidden="true">+</span></button><div id="faq-${index}" hidden><p>${item[1]}</p></div></article>`).join('')}</div><aside class="ready-card"><img src="assets/illustrations/quiz-discovery.svg" alt="" aria-hidden="true"><h2>${t('readyTitle')}</h2><p>${t('readyCopy')}</p><button class="primary-button" data-go="quiz-intro">${t('startQuiz')} ${arrow()}</button></aside></section>`);
}
function quizIntroScreen() {
  const cards = [[ 'check', t('noWrong'), t('noWrongCopy')], ['people', t('choose'), t('chooseCopy')], ['match', t('personal'), t('personalCopy')]];
  return pageShell('faq', `<section class="quiz-intro"><div class="quiz-intro-copy"><p class="eyebrow">${t('faq')}</p><h1>${t('readyTitle')}</h1><p>${t('readyCopy')}</p><section class="reassurance-grid">${cards.map(card => `<article>${icon(card[0])}<h2>${card[1]}</h2><p>${card[2]}</p></article>`).join('')}</section><button class="primary-button" data-action="start-quiz">${state.answers.some(answer => answer !== null) ? t('continueQuiz') : t('startQuiz')} ${arrow()}</button><p class="quiz-meta-line">${t('readyMeta')}</p></div><div class="quiz-intro-art"><img src="assets/illustrations/quiz-discovery.svg" alt="" aria-hidden="true"></div></section>`);
}
function quizScreen() {
  const index = state.currentQuestion; const item = questions[index][state.language]; const selected = state.answers[index]; const progress = Math.round((index + 1) / TOTAL_QUESTIONS * 100);
  return pageShell('', `<div class="journey-wrap">${progressNav('quiz')}<section class="quiz-card"><div class="quiz-topline"><span>${t('question')} <bdi>${index + 1}</bdi> ${t('of')} <bdi>${TOTAL_QUESTIONS}</bdi></span><bdi>${progress}%</bdi></div><div class="progress-track" role="progressbar" aria-label="${t('progressLabel')}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${progress}"><span style="width:${progress}%"></span></div><div class="question-dots" aria-hidden="true">${Array.from({ length: TOTAL_QUESTIONS }, (_, dot) => `<i class="${dot === index ? 'active' : state.answers[dot] !== null ? 'answered' : ''}"></i>`).join('')}</div><h1 tabindex="-1" class="quiz-question">${item.q}</h1><p class="quiz-help">${item.help}</p><div class="answer-grid" role="group" aria-label="${e(item.q)}">${item.a.map((answer, answerIndex) => `<button class="answer ${selected === answerIndex ? 'selected' : ''}" aria-pressed="${selected === answerIndex}" data-answer="${answerIndex}"><span class="round-icon">${icon(['engineering', 'people', 'innovation', 'build'][answerIndex])}</span><span><strong>${answer[0]}</strong><small>${answer[1]}</small></span>${selected === answerIndex ? `<b class="selected-mark">${icon('check')}<span class="sr-only">${t('selected')}</span></b>` : ''}</button>`).join('')}</div><div class="quiz-actions"><button class="secondary-button" data-action="quiz-back" ${index === 0 ? 'disabled' : ''}>${arrow()} ${t('back')}</button><button class="primary-button" data-action="quiz-next" ${selected === null ? 'disabled' : ''}>${index === TOTAL_QUESTIONS - 1 ? (state.language === 'en' ? 'See My Results' : 'شاهد نتائجي') : t('next')} ${arrow()}</button></div></section></div>`);
}
function resultHero(eyebrow, title, copyText) { return `<section class="result-hero"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${copyText}</p></div><img src="assets/illustrations/future-city.svg" alt="" aria-hidden="true"></section>`; }
function resultCard(item, rank, compact = false) { const x = content(item); return `<article class="result-card ${compact ? 'compact' : ''}"><div class="result-art"><img src="${item.art}" alt="" aria-hidden="true"><b class="rank">${rank}</b><span class="match-badge"><bdi>${item.result.match}%</bdi><small>${t('match')}</small></span></div><div class="result-content"><span class="round-icon">${icon(item.icon)}</span><h2>${x.name}</h2><p>${compact ? '' : x.desc}</p>${compact ? '' : `<button class="text-button" data-go="your-path">${t('view')} ${arrow()}</button>`}</div></article>`; }
function top3Screen() { const top = topEntries(); return pageShell('', `<div class="journey-wrap">${progressNav('top3')}${resultHero(t('resultsEyebrow'), t('resultsTitle'), t('resultsCopy'))}<section class="top-grid">${top.map((item, index) => resultCard(item, index + 1)).join('')}</section><div class="page-actions"><button class="secondary-button" data-action="retake">${arrow()} ${t('retake')}</button><button class="primary-button" data-go="all-fields">${t('exploreAll')} ${arrow()}</button></div></div>`); }
function allFieldsScreen() { const current = results(); const all = current.scores.map(entry => ({ ...field(entry.id), result: entry })); const top = topEntries(); return pageShell('', `<div class="journey-wrap">${progressNav('all-fields')}${resultHero(t('mapEyebrow'), t('mapTitle'), t('mapCopy'))}<section class="chart-card"><h2>${t('matchPercentages')}</h2><p>${t('mapCopy')}</p><div class="bar-chart">${all.map(item => `<div class="bar-wrap"><bdi>${item.result.match}%</bdi><div class="bar" style="--score:${item.result.match};--bar-color:${item.color}"></div><img src="${item.art}" alt="" aria-hidden="true"><span>${content(item).short}</span></div>`).join('')}</div><div class="meaning"><div><h2>${t('whatMeans')}</h2><p>${state.language === 'en' ? `Your strongest alignment is ${content(top[0]).name}, followed by ${content(top[1]).name} and ${content(top[2]).name}. These results reflect the interests and strengths you selected.` : `أقوى توافق لديك هو ${content(top[0]).name}، يليه ${content(top[1]).name} ثم ${content(top[2]).name}. تعكس هذه النتائج الاهتمامات ونقاط القوة التي اخترتها.`}</p></div><blockquote>${state.language === 'en' ? 'Your interests show a strong balance between innovation, people, and impact — key drivers for a brighter Saudi Arabia in 2030.' : 'تُظهر اهتماماتك توازنًا قويًا بين الابتكار والناس والأثر، وهي محركات مهمة لمملكة أكثر إشراقًا في عام 2030.'}</blockquote></div><h2 class="minor-heading">${t('top3')}</h2><section class="top-grid compact-grid">${top.map((item, index) => resultCard(item, index + 1, true)).join('')}</section></section><div class="page-actions"><button class="secondary-button" data-go="top3">${arrow()} ${t('top3')}</button><button class="primary-button" data-go="your-path">${t('yourPath')} ${arrow()}</button></div></div>`); }
function yourPathScreen() { const top = topEntries()[0]; const x = content(top); return pageShell('', `<div class="journey-wrap">${progressNav('your-path')}${resultHero('', t('pathTitle'), '')}<section class="path-feature"><img src="${top.art}" alt="" aria-hidden="true"><div><span class="rank">1</span><h2>${x.name}</h2><p class="match-line">${t('match')}: <bdi>${top.result.match}%</bdi></p><p>${x.impact}</p><button class="primary-button" data-go="fields">${t('fields')} ${arrow()}</button></div></section><section class="content-panel"><h2>${t('strengthDNA')}</h2><p>${state.language === 'en' ? 'These are the key strengths that align with your top field and support your success.' : 'هذه نقاط القوة الأساسية التي تتوافق مع مجالك الأعلى وتدعم نجاحك.'}</p><div class="strength-grid">${x.strengths.map((strength, index) => `<article><span class="round-icon">${icon(['sustainability', 'innovation', 'people', 'engineering'][index])}</span><h3>${strength}</h3><p>${state.language === 'en' ? 'A strength that helps you make meaningful progress and contribute with purpose.' : 'قوة تساعدك على إحراز تقدم هادف والمساهمة بغاية.'}</p></article>`).join('')}</div></section><section class="connection-panel"><div><h2>${t('connection')}</h2><p>${state.language === 'en' ? 'Your quiz answers show a strong connection between:' : 'تظهر إجاباتك في الاختبار صلة قوية بين:'}</p><div class="venn"><span>${x.short}</span><span>${state.language === 'en' ? 'Innovation' : 'الابتكار'}</span><span>${state.language === 'en' ? 'People' : 'الناس'}</span></div></div><blockquote>${state.language === 'en' ? 'This combination lets you work on meaningful solutions that improve lives and drive long-term change.' : 'يتيح لك هذا المزيج العمل على حلول هادفة تحسن الحياة وتقود تغييرًا طويل الأمد.'}</blockquote></section><section class="future-banner"><img src="${top.art}" alt="" aria-hidden="true"><div><h2>${t('futureShape')}</h2><p>${state.language === 'en' ? `Your strengths and interests position you to be a future leader in ${x.name}.` : `تضعك نقاط قوتك واهتماماتك في موقع يؤهلك لتكون قائدًا مستقبليًا في ${x.name}.`}</p></div></section><div class="page-actions"><button class="secondary-button" data-go="all-fields">${arrow()} ${t('allFields')}</button><button class="primary-button" data-go="hybrid">${t('hybrid')} ${arrow()}</button></div></div>`); }
function hybridScreen() { const combo = comboForResult(); const [first, second] = combo.fields.map(field); const a = content(first); const b = content(second); const c = content(combo); const careers = [...content(first).careers.slice(0, 3), ...content(second).careers.slice(0, 2)].slice(0, 5); return pageShell('', `<div class="journey-wrap">${progressNav('hybrid')}${resultHero('', t('hybridTitle'), t('hybridCopy'))}<section class="content-panel combination-panel"><h2>${t('combination')}</h2><div class="combination-row"><article class="combo-field"><img src="${first.art}" alt="" aria-hidden="true"><h3>${a.name}</h3><p><bdi>${resultEntry(first.id).match}%</bdi> ${t('match')}</p></article><b class="combo-symbol">+</b><article class="combo-field"><img src="${second.art}" alt="" aria-hidden="true"><h3>${b.name}</h3><p><bdi>${resultEntry(second.id).match}%</bdi> ${t('match')}</p></article><b class="combo-symbol">${arrow()}</b><article class="combo-result"><p>${t('hybrid')}</p><h3>${c.name}</h3><span>${c.desc}</span></article></div></section><section class="hybrid-meaning"><img src="assets/illustrations/future-city.svg" alt="" aria-hidden="true"><div><h2>${t('pathMeans')}</h2><p>${c.desc}</p></div></section><section class="content-panel"><h2>${t('powerful')}</h2><div class="strength-grid">${(state.language === 'en' ? [['sustainability', 'Real-World Impact'], ['engineering', 'Innovation & Growth'], ['people', 'Diverse Opportunities'], ['build', 'Supports Vision 2030']] : [['sustainability', 'أثر واقعي'], ['engineering', 'الابتكار والنمو'], ['people', 'فرص متنوعة'], ['build', 'يدعم رؤية 2030']]).map(item => `<article><span class="round-icon">${icon(item[0])}</span><h3>${item[1]}</h3><p>${state.language === 'en' ? 'Create meaningful value through practical, future-focused work.' : 'اصنع قيمة هادفة من خلال عمل عملي وموجه للمستقبل.'}</p></article>`).join('')}</div></section><section class="majors-careers"><div><h2>${t('exampleMajors')}</h2><div class="major-grid">${[...content(first).majors.slice(0, 2), content(second).majors[0]].map((major, index) => `<article><img src="${index === 0 ? first.art : second.art}" alt="" aria-hidden="true"><h3>${major}</h3><p>${state.language === 'en' ? 'Build a foundation for this personalized future path.' : 'ابنِ أساسًا لهذا المسار المستقبلي الشخصي.'}</p></article>`).join('')}</div></div><aside><h2>${t('relatedCareers')}</h2><ul>${careers.map(career => `<li>${career}<span>${arrow()}</span></li>`).join('')}</ul></aside></section><div class="page-actions"><button class="secondary-button" data-go="your-path">${arrow()} ${t('yourPath')}</button><button class="primary-button" data-go="passport">${t('passport')} ${arrow()}</button></div></div>`); }
function passportStatement(top) { const x = content(top); return state.language === 'en' ? `You are driven by a deep interest in ${x.short.toLowerCase()} and a desire to create real-world solutions. With your strengths, you can contribute to a more sustainable, resilient, and prosperous Saudi Arabia.` : `يدفعك اهتمام عميق بـ${x.short} ورغبة في ابتكار حلول واقعية. وبنقاط قوتك يمكنك الإسهام في مملكة أكثر استدامة ومرونة وازدهارًا.`; }
function passportScreen() { const top = topEntries()[0]; const combo = comboForResult(); const [first, second] = combo.fields.map(field); const x = content(top); const c = content(combo); return pageShell('', `<div class="journey-wrap passport-wrap">${progressNav('passport')}<section class="passport-card" id="passport"><header class="passport-head"><div class="passport-brand">${brand()}<small>${state.language === 'en' ? 'SAUDI ARABIA' : 'المملكة العربية السعودية'}</small></div><div><h1>${t('passportTitle')}</h1><p>${t('passportSub')}</p></div><span class="passport-stamp">VISION<br>2030</span></header><div class="passport-main"><section><p class="passport-label">${t('topField')}</p><span class="round-icon">${icon(top.icon)}</span><h2>${x.name}</h2><p class="match-line">${t('match')}: <bdi>${top.result.match}%</bdi></p><p class="passport-label">${t('topStrengths')}</p><ul class="strength-list">${x.strengths.map((strength, index) => `<li><span>${icon(['sustainability', 'innovation', 'people', 'engineering'][index])}</span>${strength}</li>`).join('')}</ul></section><section class="passport-suggestions"><blockquote>${state.language === 'en' ? 'A cleaner, brighter Saudi Arabia starts with people like you.' : 'تبدأ المملكة الأكثر إشراقًا بأشخاص مثلك.'}</blockquote><p class="passport-label">${t('suggestedMajors')}</p><ul>${x.majors.map(item => `<li>${item}</li>`).join('')}</ul><p class="passport-label">${t('suggestedCareers')}</p><ul>${x.careers.map(item => `<li>${item}</li>`).join('')}</ul></section></div><section class="passport-hybrid"><p class="passport-label">${t('hybrid')}</p><div><article><img src="${first.art}" alt="" aria-hidden="true"><span>${content(first).name}</span></article><b>+</b><article><img src="${second.art}" alt="" aria-hidden="true"><span>${content(second).name}</span></article><b>${arrow()}</b><article class="passport-combo"><span>${c.name}</span><small>${c.desc}</small></article></div></section><section class="passport-statement"><p class="passport-label">${t('personalStatement')}</p><p>${passportStatement(top)}</p></section></section><div class="page-actions no-print"><button class="secondary-button" data-go="hybrid">${arrow()} ${t('hybrid')}</button><div class="passport-actions"><button class="primary-button" data-action="print">${icon('print')} ${t('print')}</button><button class="secondary-button" data-action="share">${icon('share')} ${t('share')}</button></div></div></div>`); }

function render() {
  document.documentElement.lang = state.language; document.documentElement.dir = state.language === 'ar' ? 'rtl' : 'ltr'; document.documentElement.dataset.theme = state.theme;
  const screens = { home: homeScreen, how: howScreen, vision: visionScreen, fields: fieldsScreen, faq: faqScreen, 'quiz-intro': quizIntroScreen, quiz: quizScreen, top3: top3Screen, 'all-fields': allFieldsScreen, 'your-path': yourPathScreen, hybrid: hybridScreen, passport: passportScreen };
  app.innerHTML = screens[state.screen]?.() || homeScreen(); bindEvents();
}
function bindEvents() {
  app.querySelectorAll('[data-go]').forEach(button => button.addEventListener('click', () => goto(button.dataset.go)));
  app.querySelectorAll('[data-action="language"]').forEach(button => button.addEventListener('click', setLanguage));
  app.querySelectorAll('[data-action="theme"]').forEach(button => button.addEventListener('click', toggleTheme));
  app.querySelectorAll('[data-action="menu"]').forEach(button => button.addEventListener('click', () => { const nav = app.querySelector('.top-nav'); const open = nav.classList.toggle('open'); button.setAttribute('aria-expanded', String(open)); button.textContent = open ? '×' : '☰'; }));
  app.querySelectorAll('[data-action="faq"]').forEach(button => button.addEventListener('click', () => { const panel = document.getElementById(`faq-${button.dataset.faq}`); const open = button.getAttribute('aria-expanded') === 'true'; button.setAttribute('aria-expanded', String(!open)); panel.hidden = open; button.lastElementChild.textContent = open ? '+' : '−'; }));
  app.querySelectorAll('[data-action="start-quiz"]').forEach(button => button.addEventListener('click', startQuiz));
  app.querySelectorAll('[data-answer]').forEach(button => button.addEventListener('click', () => { state.answers[state.currentQuestion] = Number(button.dataset.answer); save(); render(); }));
  app.querySelectorAll('[data-action="quiz-back"]').forEach(button => button.addEventListener('click', () => { if (state.currentQuestion > 0) { state.currentQuestion -= 1; save(); render(); queueMicrotask(() => document.querySelector('.quiz-question')?.focus()); } }));
  app.querySelectorAll('[data-action="quiz-next"]').forEach(button => button.addEventListener('click', () => { if (state.answers[state.currentQuestion] === null) return showToast(t('answerNeeded')); if (state.currentQuestion < TOTAL_QUESTIONS - 1) { state.currentQuestion += 1; save(); render(); queueMicrotask(() => document.querySelector('.quiz-question')?.focus()); } else { state.screen = 'top3'; save(); render(); } }));
  app.querySelectorAll('[data-action="retake"]').forEach(button => button.addEventListener('click', resetQuiz));
  app.querySelectorAll('[data-action="print"]').forEach(button => button.addEventListener('click', downloadPassport));
  app.querySelectorAll('[data-action="share"]').forEach(button => button.addEventListener('click', shareResult));
}
async function downloadPassport(event) {
  const button = event.currentTarget;
  const passport = document.getElementById('passport');
  if (!passport || typeof window.html2canvas !== 'function') return showToast(t('downloadFailed'));
  button.disabled = true;
  try {
    await document.fonts?.ready;
    const images = [...passport.querySelectorAll('img')];
    await Promise.all(images.map(image => image.complete && image.naturalWidth > 0 ? Promise.resolve() : new Promise((resolve, reject) => {
      image.addEventListener('load', resolve, { once: true });
      image.addEventListener('error', reject, { once: true });
    })));
    const canvas = await window.html2canvas(passport, {
      backgroundColor: null,
      scale: 2,
      useCORS: true,
      logging: false,
      scrollX: 0,
      scrollY: 0,
      windowWidth: document.documentElement.clientWidth,
      width: passport.offsetWidth,
      height: passport.offsetHeight
    });
    const link = document.createElement('a');
    link.download = '2030-compass-result-card.png';
    link.href = canvas.toDataURL('image/png');
    document.body.append(link);
    link.click();
    link.remove();
    showToast(t('downloadReady'));
  } catch {
    showToast(t('downloadFailed'));
  } finally {
    button.disabled = false;
  }
}

async function shareResult() {
  const top = topEntries()[0]; if (!top) return;
  const summary = state.language === 'en' ? `My 2030 Compass result is ${content(top).name} — ${top.result.match}% ${t('match').toLowerCase()}.` : `نتيجتي في 2030 Compass هي ${content(top).name} بنسبة توافق ${top.result.match}٪.`;
  const local = /^(localhost|127\.0\.0\.1|0\.0\.0\.0)$/i.test(location.hostname) || location.protocol === 'file:';
  const shareData = { title: '2030 Compass', text: local ? `${summary} ${t('publicLink')}` : summary };
  if (!local) shareData.url = location.href;
  try {
    if (navigator.share) { await navigator.share(shareData); showToast(local ? t('localShare') : t('shared')); }
    else { await navigator.clipboard.writeText(local ? summary : `${summary} ${location.href}`); showToast(local ? t('localShare') : t('copied')); }
  } catch (error) {
    if (error.name === 'AbortError') return;
    try { await navigator.clipboard.writeText(local ? summary : `${summary} ${location.href}`); showToast(local ? t('localShare') : t('copied')); } catch { showToast(`${t('shareFailed')} ${summary}`); }
  }
}
render();
